# Site settings
title: Jonathon Klem
email: jonathonklem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another developer blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jonathonklem.com/" # the base hostname & protocol for your site
twitter_username: jonathonklem
github_username: jonathonklem1

permalink: /:categories/:title

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md
 
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
