#!/usr/bin/env bash
set -e # halt script on error

# check HTML 
bundle exec jekyll build
bundle exec htmlproof ./_site --href-ignore \#,http:\/\/10.10.10.10
 
# check spelling
cp .aspell.en.pws ~/
find . -iname "*.markdown" -exec cat {} \; | aspell list -d en --encoding utf-8 | sort | uniq | exit $(wc -l)
